# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bezeichner/v1/service.proto for package 'Bezeichner.V1'

require 'grpc'
require 'bezeichner/v1/service_pb'

module Bezeichner
  module V1
    module Service
      # Service allows to get a list of identifiers.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'bezeichner.v1.Service'

        # GetIdentifiers for a specific application.
        rpc :GetIdentifiers, ::Bezeichner::V1::GetIdentifiersRequest, ::Bezeichner::V1::GetIdentifiersResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
