# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bezeichner/v1/service.proto for package 'Bezeichner.V1'

require 'grpc'
require 'bezeichner/v1/service_pb'

module Bezeichner
  module V1
    module Service
      # Service allows to manage identifiers.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'bezeichner.v1.Service'

        # GenerateIdentifiers for a specific application.
        rpc :GenerateIdentifiers, ::Bezeichner::V1::GenerateIdentifiersRequest, ::Bezeichner::V1::GenerateIdentifiersResponse
        # MapIdentifiers for some identifiers.
        rpc :MapIdentifiers, ::Bezeichner::V1::MapIdentifiersRequest, ::Bezeichner::V1::MapIdentifiersResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
