# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bezeichner/v1/service.proto for package 'Bezeichner.V1'

require 'grpc'
require 'bezeichner/v1/service_pb'

module Bezeichner
  module V1
    module Service
      # Service generates and maps identifiers.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'bezeichner.v1.Service'

        # GenerateIdentifiers generates identifiers for a configured application.
        #
        # It returns InvalidArgument when count exceeds the configured limit, and
        # NotFound when the application or generator kind cannot be resolved.
        rpc :GenerateIdentifiers, ::Bezeichner::V1::GenerateIdentifiersRequest, ::Bezeichner::V1::GenerateIdentifiersResponse
        # ListApplications reports configured application names and safe capability
        # metadata.
        #
        # It does not expose mapper identifier entries, raw config, transport
        # settings, telemetry settings, or resolved secret values.
        rpc :ListApplications, ::Bezeichner::V1::ListApplicationsRequest, ::Bezeichner::V1::ListApplicationsResponse
        # MapIdentifiers maps identifiers through the configured application mapping.
        #
        # It returns InvalidArgument when more identifiers than the configured limit
        # are requested, and NotFound when mapper configuration is omitted or the
        # application is not configured.
        rpc :MapIdentifiers, ::Bezeichner::V1::MapIdentifiersRequest, ::Bezeichner::V1::MapIdentifiersResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
