# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bezeichner/v1/service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'


descriptor_data = "\n\x1b\x62\x65zeichner/v1/service.proto\x12\rbezeichner.v1\x1a\x1cgoogle/api/annotations.proto\"T\n\x1aGenerateIdentifiersRequest\x12 \n\x0b\x61pplication\x18\x01 \x01(\tR\x0b\x61pplication\x12\x14\n\x05\x63ount\x18\x02 \x01(\x04R\x05\x63ount\"/\n\x1bGenerateIdentifiersResponse\x12\x10\n\x03ids\x18\x01 \x03(\tR\x03ids\")\n\x15MapIdentifiersRequest\x12\x10\n\x03ids\x18\x01 \x03(\tR\x03ids\"*\n\x16MapIdentifiersResponse\x12\x10\n\x03ids\x18\x01 \x03(\tR\x03ids2\x9a\x02\n\x07Service\x12\x98\x01\n\x13GenerateIdentifiers\x12).bezeichner.v1.GenerateIdentifiersRequest\x1a*.bezeichner.v1.GenerateIdentifiersResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/generate/{application}/{count}\x12t\n\x0eMapIdentifiers\x12$.bezeichner.v1.MapIdentifiersRequest\x1a%.bezeichner.v1.MapIdentifiersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/map/{ids}BHZ5github.com/alexfalkowski/bezeichner/api/bezeichner/v1\xea\x02\x0e\x42\x65zeichner::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Bezeichner
  module V1
    GenerateIdentifiersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bezeichner.v1.GenerateIdentifiersRequest").msgclass
    GenerateIdentifiersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bezeichner.v1.GenerateIdentifiersResponse").msgclass
    MapIdentifiersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bezeichner.v1.MapIdentifiersRequest").msgclass
    MapIdentifiersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bezeichner.v1.MapIdentifiersResponse").msgclass
  end
end
