# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bezeichner/v1/service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("bezeichner/v1/service.proto", :syntax => :proto3) do
    add_message "bezeichner.v1.GetIdentifiersRequest" do
      optional :application, :string, 1, json_name: "application"
      optional :count, :uint64, 2, json_name: "count"
    end
    add_message "bezeichner.v1.GetIdentifiersResponse" do
      repeated :ids, :string, 1, json_name: "ids"
    end
  end
end

module Bezeichner
  module V1
    GetIdentifiersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bezeichner.v1.GetIdentifiersRequest").msgclass
    GetIdentifiersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bezeichner.v1.GetIdentifiersResponse").msgclass
  end
end
