// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bezeichner/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerateIdentifiersRequest asks the service to generate identifiers for a
// configured application.
type GenerateIdentifiersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// application is the configured generator application name.
	//
	// If the application is not configured, or if its configured kind cannot be
	// resolved, GenerateIdentifiers fails with NotFound.
	Application string `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// count is the number of identifiers to generate.
	//
	// A zero value is valid when application resolves and returns an empty ids
	// list.
	//
	// The effective maximum is configured by service operators and defaults to
	// 1000. Larger requests fail with InvalidArgument.
	Count         uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIdentifiersRequest) Reset() {
	*x = GenerateIdentifiersRequest{}
	mi := &file_bezeichner_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIdentifiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdentifiersRequest) ProtoMessage() {}

func (x *GenerateIdentifiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bezeichner_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdentifiersRequest.ProtoReflect.Descriptor instead.
func (*GenerateIdentifiersRequest) Descriptor() ([]byte, []int) {
	return file_bezeichner_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateIdentifiersRequest) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *GenerateIdentifiersRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GenerateIdentifiersResponse contains generated identifiers and service
// metadata.
type GenerateIdentifiersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta contains service and transport metadata. It is reserved for
	// infrastructure metadata and is not business data.
	//
	// Bezeichner currently returns requestId and userAgent when the transport
	// can derive them from request metadata.
	Meta map[string]string `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ids contains the generated identifiers.
	Ids           []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIdentifiersResponse) Reset() {
	*x = GenerateIdentifiersResponse{}
	mi := &file_bezeichner_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIdentifiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdentifiersResponse) ProtoMessage() {}

func (x *GenerateIdentifiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bezeichner_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdentifiersResponse.ProtoReflect.Descriptor instead.
func (*GenerateIdentifiersResponse) Descriptor() ([]byte, []int) {
	return file_bezeichner_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIdentifiersResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GenerateIdentifiersResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// MapIdentifiersRequest asks the service to map identifiers for a configured
// application.
type MapIdentifiersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// application is the configured mapper application name.
	//
	// If the application is not configured, MapIdentifiers fails with NotFound.
	Application string `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// ids contains the identifiers to map.
	//
	// An empty list is valid when application mapping configuration is present
	// and returns an empty ids list. If mapper configuration is omitted, or if
	// the application is not configured, MapIdentifiers fails with NotFound
	// before mapping.
	//
	// The effective maximum list length is configured by service operators and
	// defaults to 1000. Larger requests fail with InvalidArgument.
	Ids           []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapIdentifiersRequest) Reset() {
	*x = MapIdentifiersRequest{}
	mi := &file_bezeichner_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapIdentifiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapIdentifiersRequest) ProtoMessage() {}

func (x *MapIdentifiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bezeichner_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapIdentifiersRequest.ProtoReflect.Descriptor instead.
func (*MapIdentifiersRequest) Descriptor() ([]byte, []int) {
	return file_bezeichner_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *MapIdentifiersRequest) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *MapIdentifiersRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// MapIdentifiersResponse contains mapped and unmapped identifiers, plus service
// metadata.
type MapIdentifiersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta contains service and transport metadata. It is reserved for
	// infrastructure metadata and is not business data.
	//
	// Bezeichner currently returns requestId and userAgent when the transport
	// can derive them from request metadata.
	Meta map[string]string `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// mapped contains entries keyed by input identifier with values set to the
	// configured mapped identifier.
	Mapped map[string]string `protobuf:"bytes,2,rep,name=mapped,proto3" json:"mapped,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// unmapped contains input identifiers that could not be mapped.
	Unmapped      []string `protobuf:"bytes,3,rep,name=unmapped,proto3" json:"unmapped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapIdentifiersResponse) Reset() {
	*x = MapIdentifiersResponse{}
	mi := &file_bezeichner_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapIdentifiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapIdentifiersResponse) ProtoMessage() {}

func (x *MapIdentifiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bezeichner_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapIdentifiersResponse.ProtoReflect.Descriptor instead.
func (*MapIdentifiersResponse) Descriptor() ([]byte, []int) {
	return file_bezeichner_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *MapIdentifiersResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *MapIdentifiersResponse) GetMapped() map[string]string {
	if x != nil {
		return x.Mapped
	}
	return nil
}

func (x *MapIdentifiersResponse) GetUnmapped() []string {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

var File_bezeichner_v1_service_proto protoreflect.FileDescriptor

const file_bezeichner_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bbezeichner/v1/service.proto\x12\rbezeichner.v1\"T\n" +
	"\x1aGenerateIdentifiersRequest\x12 \n" +
	"\vapplication\x18\x01 \x01(\tR\vapplication\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\xb2\x01\n" +
	"\x1bGenerateIdentifiersResponse\x12H\n" +
	"\x04meta\x18\x01 \x03(\v24.bezeichner.v1.GenerateIdentifiersResponse.MetaEntryR\x04meta\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x15MapIdentifiersRequest\x12 \n" +
	"\vapplication\x18\x01 \x01(\tR\vapplication\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"\xb8\x02\n" +
	"\x16MapIdentifiersResponse\x12C\n" +
	"\x04meta\x18\x01 \x03(\v2/.bezeichner.v1.MapIdentifiersResponse.MetaEntryR\x04meta\x12I\n" +
	"\x06mapped\x18\x02 \x03(\v21.bezeichner.v1.MapIdentifiersResponse.MappedEntryR\x06mapped\x12\x1a\n" +
	"\bunmapped\x18\x03 \x03(\tR\bunmapped\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vMappedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xda\x01\n" +
	"\aService\x12n\n" +
	"\x13GenerateIdentifiers\x12).bezeichner.v1.GenerateIdentifiersRequest\x1a*.bezeichner.v1.GenerateIdentifiersResponse\"\x00\x12_\n" +
	"\x0eMapIdentifiers\x12$.bezeichner.v1.MapIdentifiersRequest\x1a%.bezeichner.v1.MapIdentifiersResponse\"\x00BHZ5github.com/alexfalkowski/bezeichner/api/bezeichner/v1\xea\x02\x0eBezeichner::V1b\x06proto3"

var (
	file_bezeichner_v1_service_proto_rawDescOnce sync.Once
	file_bezeichner_v1_service_proto_rawDescData []byte
)

func file_bezeichner_v1_service_proto_rawDescGZIP() []byte {
	file_bezeichner_v1_service_proto_rawDescOnce.Do(func() {
		file_bezeichner_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bezeichner_v1_service_proto_rawDesc), len(file_bezeichner_v1_service_proto_rawDesc)))
	})
	return file_bezeichner_v1_service_proto_rawDescData
}

var file_bezeichner_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bezeichner_v1_service_proto_goTypes = []any{
	(*GenerateIdentifiersRequest)(nil),  // 0: bezeichner.v1.GenerateIdentifiersRequest
	(*GenerateIdentifiersResponse)(nil), // 1: bezeichner.v1.GenerateIdentifiersResponse
	(*MapIdentifiersRequest)(nil),       // 2: bezeichner.v1.MapIdentifiersRequest
	(*MapIdentifiersResponse)(nil),      // 3: bezeichner.v1.MapIdentifiersResponse
	nil,                                 // 4: bezeichner.v1.GenerateIdentifiersResponse.MetaEntry
	nil,                                 // 5: bezeichner.v1.MapIdentifiersResponse.MetaEntry
	nil,                                 // 6: bezeichner.v1.MapIdentifiersResponse.MappedEntry
}
var file_bezeichner_v1_service_proto_depIdxs = []int32{
	4, // 0: bezeichner.v1.GenerateIdentifiersResponse.meta:type_name -> bezeichner.v1.GenerateIdentifiersResponse.MetaEntry
	5, // 1: bezeichner.v1.MapIdentifiersResponse.meta:type_name -> bezeichner.v1.MapIdentifiersResponse.MetaEntry
	6, // 2: bezeichner.v1.MapIdentifiersResponse.mapped:type_name -> bezeichner.v1.MapIdentifiersResponse.MappedEntry
	0, // 3: bezeichner.v1.Service.GenerateIdentifiers:input_type -> bezeichner.v1.GenerateIdentifiersRequest
	2, // 4: bezeichner.v1.Service.MapIdentifiers:input_type -> bezeichner.v1.MapIdentifiersRequest
	1, // 5: bezeichner.v1.Service.GenerateIdentifiers:output_type -> bezeichner.v1.GenerateIdentifiersResponse
	3, // 6: bezeichner.v1.Service.MapIdentifiers:output_type -> bezeichner.v1.MapIdentifiersResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bezeichner_v1_service_proto_init() }
func file_bezeichner_v1_service_proto_init() {
	if File_bezeichner_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bezeichner_v1_service_proto_rawDesc), len(file_bezeichner_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bezeichner_v1_service_proto_goTypes,
		DependencyIndexes: file_bezeichner_v1_service_proto_depIdxs,
		MessageInfos:      file_bezeichner_v1_service_proto_msgTypes,
	}.Build()
	File_bezeichner_v1_service_proto = out.File
	file_bezeichner_v1_service_proto_goTypes = nil
	file_bezeichner_v1_service_proto_depIdxs = nil
}
