// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        (unknown)
// source: bezeichner/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetIdentifiersRequest for a specific application.
type GetIdentifiersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Application string `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Count       uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetIdentifiersRequest) Reset() {
	*x = GetIdentifiersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bezeichner_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentifiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentifiersRequest) ProtoMessage() {}

func (x *GetIdentifiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bezeichner_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentifiersRequest.ProtoReflect.Descriptor instead.
func (*GetIdentifiersRequest) Descriptor() ([]byte, []int) {
	return file_bezeichner_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetIdentifiersRequest) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *GetIdentifiersRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetIdentifierResponse for a specific application.
type GetIdentifiersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetIdentifiersResponse) Reset() {
	*x = GetIdentifiersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bezeichner_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentifiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentifiersResponse) ProtoMessage() {}

func (x *GetIdentifiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bezeichner_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentifiersResponse.ProtoReflect.Descriptor instead.
func (*GetIdentifiersResponse) Descriptor() ([]byte, []int) {
	return file_bezeichner_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetIdentifiersResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_bezeichner_v1_service_proto protoreflect.FileDescriptor

var file_bezeichner_v1_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x62, 0x65, 0x7a, 0x65, 0x69, 0x63, 0x68, 0x6e, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62,
	0x65, 0x7a, 0x65, 0x69, 0x63, 0x68, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x32, 0x90, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x84, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x24, 0x2e, 0x62, 0x65, 0x7a, 0x65, 0x69, 0x63, 0x68,
	0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62,
	0x65, 0x7a, 0x65, 0x69, 0x63, 0x68, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x12, 0x1d, 0x2f, 0x76, 0x31,
	0x2f, 0x69, 0x64, 0x73, 0x2f, 0x7b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x7d, 0x2f, 0x7b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x7d, 0x42, 0x48, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x78, 0x66, 0x61, 0x6c,
	0x6b, 0x6f, 0x77, 0x73, 0x6b, 0x69, 0x2f, 0x62, 0x65, 0x7a, 0x65, 0x69, 0x63, 0x68, 0x6e, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x65, 0x7a, 0x65, 0x69, 0x63, 0x68, 0x6e, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0xea, 0x02, 0x0e, 0x42, 0x65, 0x7a, 0x65, 0x69, 0x63, 0x68, 0x6e, 0x65, 0x72,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bezeichner_v1_service_proto_rawDescOnce sync.Once
	file_bezeichner_v1_service_proto_rawDescData = file_bezeichner_v1_service_proto_rawDesc
)

func file_bezeichner_v1_service_proto_rawDescGZIP() []byte {
	file_bezeichner_v1_service_proto_rawDescOnce.Do(func() {
		file_bezeichner_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bezeichner_v1_service_proto_rawDescData)
	})
	return file_bezeichner_v1_service_proto_rawDescData
}

var file_bezeichner_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bezeichner_v1_service_proto_goTypes = []interface{}{
	(*GetIdentifiersRequest)(nil),  // 0: bezeichner.v1.GetIdentifiersRequest
	(*GetIdentifiersResponse)(nil), // 1: bezeichner.v1.GetIdentifiersResponse
}
var file_bezeichner_v1_service_proto_depIdxs = []int32{
	0, // 0: bezeichner.v1.Service.GetIdentifiers:input_type -> bezeichner.v1.GetIdentifiersRequest
	1, // 1: bezeichner.v1.Service.GetIdentifiers:output_type -> bezeichner.v1.GetIdentifiersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bezeichner_v1_service_proto_init() }
func file_bezeichner_v1_service_proto_init() {
	if File_bezeichner_v1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bezeichner_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdentifiersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bezeichner_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdentifiersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bezeichner_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bezeichner_v1_service_proto_goTypes,
		DependencyIndexes: file_bezeichner_v1_service_proto_depIdxs,
		MessageInfos:      file_bezeichner_v1_service_proto_msgTypes,
	}.Build()
	File_bezeichner_v1_service_proto = out.File
	file_bezeichner_v1_service_proto_rawDesc = nil
	file_bezeichner_v1_service_proto_goTypes = nil
	file_bezeichner_v1_service_proto_depIdxs = nil
}
