#!/usr/bin/env bash

set -e

latest_tag=$(git tag | sort -V | tail -1)

# Build and push docker.
docker build --build-arg version="$latest_tag" -t alexfalkowski/bezeichner -t alexfalkowski/bezeichner:"$latest_tag" .
docker push alexfalkowski/bezeichner --all-tags
